### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by karolmajek** [PeterL1n/BackgroundMattingV2#1]
Please include license file in this repo

**Comment by senguptaumd** [comment]
Added.
This work is licensed under the Creative Commons Attribution NonCommercial ShareAlike 4.0 License.

**Comment by Calinou** [comment]
> This work is licensed under the Creative Commons Attribution NonCommercial ShareAlike 4.0 License.

Please consider using a free license that allows commercial use. This would allow easier use in open source projects, since non-commercial clauses are incompatible with open source by definition. See [this page](https://freedomdefined.org/Licenses/NC) for more information.
