### ISSUE TITLE
Can this code work without GPU cuda?

### ISSUE THREAD

**Issue by gogov5** [PeterL1n/BackgroundMattingV2#10]
Dear, 
Can this code work without GPU cuda?  I only want to use it on single picture 

thanks

**Comment by PeterL1n** [comment]
You can certainly run the code using CPU, but it would be slower.

**Comment by PeterL1n** [comment]
I just updated the inference scripts. Please do a pull.

You can now use `inference_video.py` and `inference_images.py` with an additional argument `--device cpu` to use CPU for inference.

**Comment by gogov5** [comment]
> I just updated the inference scripts. Please do a pull.
> 
> You can now use `inference_video.py` and `inference_images.py` with an additional argument `--device cpu` to use CPU for inference.

so nice, got it

**Comment by gogov5** [comment]
by the way, which version of Torch is used?    I use 1.3 to load model, get RuntimeError    thanks

**Comment by PeterL1n** [comment]
Use PyTorch 1.7, as specified in `requirements.txt`.
