### ISSUE TITLE
请问可以分布式计算吗？

### ISSUE THREAD

**Issue by zhanghonglishanzai** [PeterL1n/BackgroundMattingV2#102]
您好，我现在手里有8块3090的GPU卡，我修改了以下代码
model = model.to(device).eval()
model.load_state_dict(torch.load(args.model_checkpoint, map_location=device), strict=False)
为
model = model.to(device).eval()
BM = model.load_state_dict(torch.load(args.model_checkpoint, map_location=device), strict=False)
BM = nn.DataParallel(BM)

我不知道修改的对不对

我在运行程序的时候监测GPU的使用状况，发现只有一张卡在使用，求指点

**Comment by zhanghonglishanzai** [comment]
model = model.to(device).eval()
BM = model.load_state_dict(torch.load(args.model_checkpoint, map_location=device), strict=False)
device_ids = [0, 1，2，3，4，5，6，7]
BM = nn.DataParallel(BM, device_ids=device_ids)

我改成这样，还是不行

**Comment by PeterL1n** [comment]
如果你还是用`inference_video.py`，你可能要改182行`batch_size=1`为更大的batch_size。

**Comment by PeterL1n** [comment]
但 inference_video.py 的视频编解码都不是多线程优化的，可能瓶颈是在视频的编解码而不是GPU。如果是这呀，你要自己写这方面的代码了。

**Comment by PeterL1n** [comment]
你方便说你是什么一个用途吗？

**Comment by zhanghonglishanzai** [comment]
我们是一个与zoom的视频会议平台，然后希望实时的对参会人员的背景进行实时的替换

**Comment by zhanghonglishanzai** [comment]
我这边是复杂算法对接的，编解码那边还有视频组的人在做，我一会儿修改一下batch_size，如果还是单GPU的话，就不归我这边管了，就需要在编解码那边去优化了，他们那边据说有很成熟的方案

**Comment by zhanghonglishanzai** [comment]
十分感谢你的解答，我晚些给你修改batch_size=1之后的结果

**Comment by zhanghonglishanzai** [comment]
小哥哥，你好，我又来了

我先和你说一下我遇到的问题，我用自己拍出来的视频做实验，得到的效果，和，在官网上下载到的你们paper中做实验用的视频得到的效果，相差的太多了，我就是想知道原因，是我的参数设置的有问题，还是对于拍摄的视频有什么要求吗？还是对视频做了什么处理呀，我们做出来的视频真的是惨不忍睹啊




我说一下我的实验环境啊，小哥哥，cuda 11.0 pytorch 1.7 3090的卡，多张，不过目前还是在一张卡上跑，然后附件中我会附上，我们同事拍的视频和背景照片，还有运行出来的结果。




python /home/ubuntu/BM/BackgroundMattingV2/inference_video_only.py \
&nbsp; &nbsp; &nbsp; &nbsp; --model-type mattingrefine \
&nbsp; &nbsp; &nbsp; &nbsp; --model-backbone resnet50 \
&nbsp; &nbsp; &nbsp; &nbsp; --model-backbone-scale 0.25 \
&nbsp; &nbsp; &nbsp; &nbsp; --model-refine-mode sampling \
&nbsp; &nbsp; &nbsp; &nbsp; --model-refine-sample-pixels 80000 \
&nbsp; &nbsp; &nbsp; &nbsp; --model-checkpoint "/home/ubuntu/BM/pytorch_resnet50.pth" \
&nbsp; &nbsp; &nbsp; &nbsp; --video-src "/home/ubuntu/BM/huangfupeng/720/720.mp4" \
&nbsp; &nbsp; &nbsp; &nbsp; --video-bgr "/home/ubuntu/BM/huangfupeng/img/新建文件夹/3_720.bmp" \
&nbsp; &nbsp; &nbsp; &nbsp; --output-dir "/home/ubuntu/BM/content/output/2021051910_720/" \
&nbsp; &nbsp; &nbsp; &nbsp; --output-type com






fig1. 这个是用res50模型，1080的像素(视频和背景照片)运行出来的实验结果



从QQ邮箱发来的超大附件

实验视频.rar (211.32M, 2021年06月24日 14:50 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7263346520bcf8c792ab977b1566001a51005756015e53011e5a0456004b06045001195d0b0402180651075c5004025105540104336a32ff86b2ddafe0a0871b410246650e&code=3c4e3f25




原数据.rar (113.00M, 2021年06月24日 14:52 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0e626431b6c5db9c90aac72f1735064b550305020203075c1c5a0600091800020857490954010749015154035050000006560707313f34b09ca8998fec1b4605436259&code=1bd1154d
