### ISSUE TITLE
UserWarning: Argument fill/fillcolor is not supported for Tensor input. Fill value is zero

### ISSUE THREAD

**Issue by bianxg** [PeterL1n/BackgroundMattingV2#105]
What is the impact of this warning? Thank.

root/anaconda2/envs/matting/lib/python3.8/site-packages/torchvision/transforms/functional_tensor.py:876: UserWarning: Argument fill/fillcolor is not supported for Tensor input. Fill value is zero
  warnings.warn("Argument fill/fillcolor is not supported for Tensor input. Fill value is zero")

`>>> import torch
>>> print(torch.__version__)
1.7.0
>>> print(torch.cuda.is_available())
True`

`CUDA_VISIBLE_DEVICES=0 python train_base.py \
    --dataset-name videomatte240k \
    --model-backbone resnet50 \
    --model-name mattingbase-resnet50-videomatte240k \
    --model-pretrain-initialization "/mnt/data/matting/pretrain/best_deeplabv3_resnet50_voc_os16.pth" \
    --epoch-end 8`

**Comment by PeterL1n** [comment]
Most likely can be ignored.
