### ISSUE TITLE
How to obtain Adobe Image Matting dataset's background?

### ISSUE THREAD

**Issue by MrDavinci** [PeterL1n/BackgroundMattingV2#109]
I want to use your model on AIM, but your model need original image background.
How did you extract them?
Just (1-alpha)*original_image ?

**Comment by MrDavinci** [comment]
Sorry, I mean when I'm using model to inferrence on AIM test, I need extract AIM imags' backgrounds,
What did you do that?

**Comment by PeterL1n** [comment]
Testing is also done by compositing.

**Comment by MrDavinci** [comment]
"Our model requires capturing an additional background image .........."
I am confused. So if I want to test the model, I just put the original image with another new background rather than
the original image's background?

**Comment by PeterL1n** [comment]
For testing, lets say AIM provide ground-truth alpha and foreground. You find yourself a background image. Then you composite the foreground and background together to form your input image.

You give the model the input image and the background image, then the model predicts the alpha and foreground. Then you can measure how well is the alpha and foreground prediction regard to the ground-truth given by AIM.

**Comment by MrDavinci** [comment]
lol............
Thanks, get
