### ISSUE TITLE
no right result

### ISSUE THREAD

**Issue by luoww1992** [PeterL1n/BackgroundMattingV2#11]
i have done it with inference_video.py.
cmd is:
    python inference_video.py \
        --model-type mattingrefine \
        --model-backbone resnet50 \
        --model-backbone-scale 0.25 \
        --model-refine-mode sampling \
        --model-refine-sample-pixels 80000 \
        --model-checkpoint ./pytorch_resnet50.pth \
        --video-src ./test/test.mp4 \
        --video-bgr ./test/bg.png \
        --video-resize 1920 1080 \
        --output-dir output \
        --output-type com
i use the er1.mp4 you given and a new bg image.
 i use the default seettings --> com = fgr * pha + bgr_green * (1 - pha)
 and myself --> com = pha * fgr + (1 - pha) * bgr
And i get the results.
But the two com.mp4 are the same as the input src mp4---video-src ./test/test.mp4
it looks like no different in com.mp4.
the bg  has no changed.
what happened ?

**Comment by PeterL1n** [comment]
Are you using the provided `inference_video.py` script without modification? The provided background `--video-bgr` must be the actual background of the video, not a new background. Our method requires an input video and a pre-captured background of that video without the subject to generate high-quality matting. If you are trying `er1.mp4`, make sure you provide `er1.png` as background, which can be found in google drive.

**Comment by luoww1992** [comment]
i see it in google drive. i run it in google colab.it is right we need the same bg in mp4 and image.
then i have a question: 
how we need to do if  the bg is  dynamic ?

**Comment by PeterL1n** [comment]
What is the reason you need the background to be dynamic?

It is rare that you need the background to be dynamic. Most of the use cases are that if you have a handheld video, you will want a dynamic background where each frame is aligned with the video frame. We actually provide this functionally in `inference_videos.py`, you just need to add `--preprocess-alignment`

If you really want the background to be a video, the model can totally do it, as we process the video frame by frame and you just need to provide the model the corresponding frame of the background. The inference script provided does not have this functionally, you will need to code it up yourself.
