### ISSUE TITLE
Rotoscope cartoon/anime?

### ISSUE THREAD

**Issue by krigeta** [PeterL1n/BackgroundMattingV2#116]
is it possible to do rotoscoping on cartoon or anime using this?

**Comment by fingerx** [comment]
@krigeta any news?

**Comment by PeterL1n** [comment]
Not with the given models. They are not trained for this purposes. Unless you want to curate your own dataset and train a model yourself.

**Comment by krigeta** [comment]
> Not with the given models. They are not trained for this purposes. Unless you want to curate your own dataset and train a model yourself.

Okay then may you please tag me some info on how to train it and what type of dataset is good for it? that would be helpful.
