### ISSUE TITLE
Refiner seems to be a double edge sword

### ISSUE THREAD

**Issue by jazzseow** [PeterL1n/BackgroundMattingV2#117]
I have trained a model with my own dataset. I noticed that the refiner does a very good job in patching missing area and removing noise. But the edges become rugged. 

Even when i test with the model provided, comparing the edges only, there seems to be little improve, and sometimes i feel that mattingbase performs better than mattingrefine.

Do you experience this too?

**Comment by PeterL1n** [comment]
> I feel that mattingbase performs better than mattingrefine.

MattingBase is limited to low-resolution. MattingRefine can do high resolution. I don't think you can directly compare the two. If your video is low-res, then just use MattingBase. If your video is high-res, then applying MattingBase directly is too computationally expensive.

**Comment by jazzseow** [comment]
Thank you for explaining, seems like I misunderstood the purpose of refiner.

**Comment by YuLiHN** [comment]
Hello jazzseow, I have the same question as you. When I trained the refine network like 20 epochs, other patch did perform better, but the edge of person become rugged. This kind of situation raises and becomes more serious with the epoch going up. I think my dataset is quite high resolution (3840x5120). Here is an example:
![image](https://user-images.githubusercontent.com/82912827/122564916-2f9c6980-d046-11eb-93fe-26d77286b96f.png)

How do you solve this?

**Comment by PeterL1n** [comment]
@YuLiHN 

Increase the refiner sample pixels! The artifact in your image happens because the sample pixels value is set too low, and many pixels that are not at the immediate edge don't get refined.

**Comment by YuLiHN** [comment]
> @YuLiHN
> 
> Increase the refiner sample pixels! The artifact in your image happens because the sample pixels value is set too low, and many pixels that are not at the immediate edge don't get refined.

Thanks for your advice! It did work!
