### ISSUE TITLE
model license?

### ISSUE THREAD

**Issue by ai-Ilike** [PeterL1n/BackgroundMattingV2#118]
Hello! Thank you so much for sharing the code and the model.

I would like to ask, what protocol is the pre-training model? Can I use it in a business project?

Your reply is very much needed.

**Comment by StephenHnilica** [comment]
I'm not the project owner, but you can check the rights here: https://github.com/PeterL1n/BackgroundMattingV2/blob/master/LICENSE

Not a lawyer, but from what I understand, it's under an MIT License, meaning you can use it for whatever purpose you see fit, but you develop with this must also be under the MIT license.

**Comment by PeterL1n** [comment]
You can use it for commercial purposes. Your product **DOES NOT** need to be MIT open source, meaning that you can use it in whatever closed-source software you like free of charge. The only thing is that we do not provide a warrenty.
