### ISSUE TITLE
paper details discuss

### ISSUE THREAD

**Issue by Ontheway361** [PeterL1n/BackgroundMattingV2#119]
What is the purpose of inputing the background image into the network? if there is no background image, then how to infer ?

**Comment by PeterL1n** [comment]
The background simplifies the matting problem (high-resolution hair detail) and acts as an implicit way to select matting targets. This method is specifically designed for background matting. You cannot infer without a pre-captured background.

We have a follow-up work planning to release in August or September this year with significant improvements in speed and robustness. The method will no longer require a pre-captured background. Stay tuned.

**Comment by Ontheway361** [comment]
> The background simplifies the matting problem (high-resolution hair detail) and acts as an implicit way to select matting targets. This method is specifically designed for background matting. You cannot infer without a pre-captured background.
> 
> We have a follow-up work planning to release in August or September this year with significant improvements in speed and robustness. The method will no longer require a pre-captured background. Stay tuned.

wow. Thank your reply very much and look forward to the new job.
