### ISSUE TITLE
一些训练时的细节

### ISSUE THREAD

**Issue by YuLiHN** [PeterL1n/BackgroundMattingV2#120]
大佬你好，我现在已经解决分割的边缘有很多锯齿状的问题，现在还有几个问题想要跟你请教下。

1. 我用训练出来的模型做分割，当我的前景跟背景颜色很像的时候效果就很差(比如当人物穿了白色袜子背景也是白色的时候)。我猜测是因为训练时我的背景很单调的缘故，因为pretrained模型没有这个问题。你觉得我增加一些背景，加入一些复杂场景和文理的背景图片会不会好一些？
2. 关于backbone scale这个参数的调参。我之前通过调节k，也就是refine sample pixel这个值到1,000,000解决了边缘的问题。但是我很疑惑的是backbone scale 0.2的时候表现的很好，0.1的时候反而不好了。请问调节这个参数有什么经验吗？

**Comment by PeterL1n** [comment]
1. 最直接的就是在训练时加入更多此类的 samples。让背景和前景有类似的颜色。还有就是可以将背景做一些颜色或位移的 augmentation，因为在现实中提供背景图并不会和 image 的每一个像素完美一致。
2. backbone scale 和 refine sample pixels 都要根据你的分辨率调整。若 1920x1080 输入，backbone_scale=0.25, 这样实际上就是给 encoder 时候缩小4倍，成 480x270，这个分辨率在 256-512 之间，是 training 时候的大小。我们推荐 1920x1080 用 0.25 / 80,000，3840x2160 用 0.125 / 320,000

**Comment by YuLiHN** [comment]
谢谢你的建议。大佬加油，follow 你了
