### ISSUE TITLE
Question rather than an issue.

### ISSUE THREAD

**Issue by SetoKayaba** [PeterL1n/BackgroundMattingV2#127]
I'm trying to create my own adaptation of this code and while the docs are clear are concise, I'd like to know how the bgr and source fit into it, could I get an example implementation. I don't like to use the inference, truelly feels like using a black box but rather have more control over the code.

**Comment by PeterL1n** [comment]
See the colab example: https://colab.research.google.com/drive/1cTxFq1YuoJ5QPqaTcnskwlHDolnjBkB9?usp=sharing

**Comment by SetoKayaba** [comment]
Thanks for the Reply Mr. Peter,
The issue is this one uses inference, I was hoping on working with the code directly. Also have you considered partnering up with colab to deliver this as an application with the support of clouds free GPU resources?

**Comment by SetoKayaba** [comment]
nvm my bad this is the one I want! Thanks alot

**Comment by SetoKayaba** [comment]
from here the next step would be on dealing with several batches of images and running them as frames and then adding the frames together the create the video. makes sense. thanks

**Comment by SetoKayaba** [comment]
> 
> 
> See the colab example: https://colab.research.google.com/drive/1cTxFq1YuoJ5QPqaTcnskwlHDolnjBkB9?usp=sharing

I have a question this is the non inference adaptation for the image matting example but does a non inference adaption for a video matting example exist? Assuming I apply the image adaptation to individual video frames, I believe this would take too long to create.

**Comment by SetoKayaba** [comment]
are you using the same technique I referred to in the above comment for the video inference example and real-time streaming plugin? Also have you considered extracting the background image/video through object recognition and grabcut algorithm?

**Comment by PeterL1n** [comment]
For this model, you can process video as images on every frame using a for loop.

You can try background extraction yourself. We provide guidance on that.

In September this year, we will release a new model that does not require background and achieves new state-of-the-art.
