### ISSUE TITLE
Questions about the pre-trained model关于预训练模型，base部分的模型是没有提供吗？

### ISSUE THREAD

**Issue by jinyue123** [PeterL1n/BackgroundMattingV2#129]
作者您好：
        我在您上传的model/pytorch里边，只看到了refine后预训练好的模型，但是没有看到第一阶段base部分预训练好的模型，想问一下方便提供一下吗？
        另外，如果对绿幕下拍摄的素材进行处理的话，好像绿色溢出现象还是很严重的，请问这个问题这篇论文是不是还不能解决呢？
期待回复！

Dear author:

In the model/ PyTorch you uploaded, I only saw the pre-trained model after Refine, but not the pre-trained model in the base part of the first stage. Could you please provide me with some information?

In addition, if the material shot under the green screen is processed, it seems that the green overflow phenomenon is still very serious. May I ask whether this paper can not solve this problem?

Looking forward to your reply!

**Comment by PeterL1n** [comment]
1.
Weights for base is included in refined models
```python
model = MattingBase('resnet50')
model.load_state_dict(torch.load('refined.pth'), strict=False) # use strict=False to ignore refiner weights when loading.
```

2. Not sure.
