### ISSUE TITLE
Can this model used for other object background matting？

### ISSUE THREAD

**Issue by gogov5** [PeterL1n/BackgroundMattingV2#13]
Can this model used for other objects background matting？  I try other object eg. toys,  the results seem not expected   
Now, this model is only for body?

thanks

**Comment by PeterL1n** [comment]
The model is only trained for human matting.

**Comment by gogov5** [comment]
> The model is only trained for human matting.

Thanks， Looking forward  your training code~  . I want to use for special object background matting.
