### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by hqqxyy** [PeterL1n/BackgroundMattingV2#136]
Hi,

Great job!

For a fair comparison, is it possible to share the evaluation metrics code in the paper? 

Thanks

**Comment by PeterL1n** [comment]
@andreyryabtsev Do you still have the eval script?

**Comment by hqqxyy** [comment]
Thanks! Here is my email: qiqi2@pdx.edu. You can share with me the functions to get the MSE, SAD, Grad, Conn for alpha. and MSE for FG.

**Comment by Datura0822** [comment]
Hi, i also need  the evaluation metrics code in the paper. Can you share with me the functions to get the MSE, SAD, Grad, Conn for alpha ? And MSE for FG ?

**Comment by PeterL1n** [comment]
I will upload the code to GitHub repo later for everyone's use then.

**Comment by PeterL1n** [comment]
I have uploaded the eval code used by @andreyryabtsev to `/eval` folder.

We simply used the Matlab/Octave code provided by https://openaccess.thecvf.com/content_cvpr_2017/html/Xu_Deep_Image_Matting_CVPR_2017_paper.html

**Comment by Datura0822** [comment]
Thank you very much!

**Comment by newjavaer** [comment]
> Thank you very much!

你是怎么算指标的啊，相比三分图只计算边缘部分的像素，
