### ISSUE TITLE
What is the argument for 4K footage ?

### ISSUE THREAD

**Issue by BracerJack** [PeterL1n/BackgroundMattingV2#138]
I am currently using:
python inference_video.py --model-type mattingrefine --model-backbone resnet50 --model-checkpoint ./model/PyTorch/pytorch_resnet50.pth --model-refine-sample-pixels 320_000 --video-src ./input/Raw.avi --video-bgr ./input/Empty_Background.png --output-dir ./output --output-types com fgr pha err ref

So far it works VERY WELL.

But sometimes when the gap is small, the cut out will not be made probably because the sample is too low ?
What modifications should I make to the command line statement that I use on top to make it really good for 4K footage ?
I don't care if it is not real time, I care more about the cut out quality, it can take AS LONG AS IT TAKES, Quality comes first :D

**Comment by PeterL1n** [comment]
4K I would use `--model-backbone-scale 0.125`. Sample pixels 320000 is fine.

**Comment by BracerJack** [comment]
Can I confirm that the whole statement would be:
python inference_video.py --model-type mattingrefine --model-backbone resnet50 --model-checkpoint ./model/PyTorch/pytorch_resnet50.pth --model-backbone-scale 0.125 320_000 --video-src ./input/Raw.avi --video-bgr ./input/Empty_Background.png --output-dir ./output --output-types com fgr pha err ref

Thanks.

**Comment by PeterL1n** [comment]
You missed `--model-refine-sample-pixels`. Other than that it's good.

**Comment by BracerJack** [comment]
Where do I put that ? Before or after the --model-backbone-scale 0.125 320_000 ?
Can you give me the full complete statement ?

**Comment by PeterL1n** [comment]
This should be good, but I haven't tested it myself.

```
python inference_video.py --model-type mattingrefine --model-backbone resnet50 --model-checkpoint ./model/PyTorch/pytorch_resnet50.pth --model-backbone-scale 0.125 --model-refine-sample-pixels 320_000 --video-src ./input/Raw.avi --video-bgr ./input/Empty_Background.png --output-dir ./output --output-types com fgr pha err ref
```
