### ISSUE TITLE
Torchscript production code doesn't seem to work correctly

### ISSUE THREAD

**Issue by MaxHarris76** [PeterL1n/BackgroundMattingV2#139]
Hello, I have attempted to use the Torchsc
ript production code to perform image matting however I am receiving my composite image the same as the original source image. Here is a screenshot of my code with the outputted composition image that is the same as my inputted src.jpg file. Is there anything I am specifically doing wrong or is there an error somewhere with the pretrained model? Any help provided is greatly appreciated, thank you!
![github issue bgmatt](https://user-images.githubusercontent.com/51440573/126910597-dc5b6754-fb52-4587-bdea-8c324b936616.JPG)

**Comment by PeterL1n** [comment]
Make sure the background image is the actual background of the input, not the target background you want to composite on.
