### ISSUE TITLE
about the evaluation code

### ISSUE THREAD

**Issue by Datura0822** [PeterL1n/BackgroundMattingV2#140]
@PeterL1n 

Hi, thanks for your great job. I want to know if trimap is used in your evaluation code. Is it possible to share with me the functions to get the MSE, SAD, Grad, Conn for alpha ? And MSE for FG ?

Here is my email: 1325655051@qq.com. Thank you very much.

**Comment by PeterL1n** [comment]
See #136.

**Comment by PeterL1n** [comment]
Trimap was used in evaluating. We only evaluated the gray region.

**Comment by Datura0822** [comment]
OK, i get it. Thank you very much.
