### ISSUE TITLE
About the result in this paper

### ISSUE THREAD

**Issue by Datura0822** [PeterL1n/BackgroundMattingV2#141]
Hi, this is a grest job!

![image](https://user-images.githubusercontent.com/23152332/127289126-d4c0baea-52d4-4f4d-afe0-e955d5a952d3.png)

I want to know what experimental settings can get the above results.

I use the dataset AIM and experimental setting like this, but cannot get the result which should be close to your paper.

python inference_images.py \
    --model-type mattingrefine \
    --model-backbone resnet50 \
    --model-backbone-scale 0.25 \
    --model-refine-mode sampling \
    --model-refine-sample-pixels 320000 \
    --model-checkpoint "/home/ray/host/guog/pytorch_resnet50.pth" \
    --images-src "/home/ray/host/guog/adobe_test_merged/img/" \
    --images-bgr "/home/ray/host/guog/adobe_test_merged/bgr/" \
    --output-dir "/home/ray/host/guog/results/adobe_test/mattingrefine_adobe_pytorch_resnet50/" \
    --output-type fgr pha

And my result like this, 

sad: 86.74472909411772
mse: 0.04342306696238956
grad: 75696.20515350341
conn: 89876.03669165046

**Comment by Datura0822** [comment]
I use the weights download from your https://drive.google.com/

**Comment by PeterL1n** [comment]
Can you confirm that you have only used human samples from AIM (remove non human samples) and composited the images using our validation background dataset?

**Comment by Datura0822** [comment]
Sorry, I did not remove the non-human images. 

I used an image I took as a background. Will this have a big impact on the result? I guess it should not. I will try to verify it.

I used your evaluation metric code.

**Comment by Yiir-1** [comment]
@Datura0822  hi！ I want to run the evaluation metric code in this project ,but i have not seen this kind of ".m" code before, and i do not know how to run it  . Could you help me please, it’s too much trouble for you.
