### ISSUE TITLE
4K settings as suggested by PeterL1n gives worst result.

### ISSUE THREAD

**Issue by BracerJack** [PeterL1n/BackgroundMattingV2#145]
Default Setting:
python inference_video.py --model-type mattingrefine --model-backbone resnet50 --model-checkpoint ./model/PyTorch/pytorch_resnet50.pth --model-refine-sample-pixels 320_000 --video-src ./input/Raw.avi --video-bgr ./input/Empty_Background.png --output-dir ./output --output-types com fgr pha err ref

4K Setting:
python inference_video.py --model-type mattingrefine --model-backbone resnet50 --model-checkpoint ./model/PyTorch/pytorch_resnet50.pth --model-backbone-scale 0.125 --model-refine-sample-pixels 320_000 --video-src ./input/Raw.avi --video-bgr ./input/Empty_Background.png --output-dir ./output --output-types com fgr pha err ref

Footage is 4K, the 4K settings makes the 4K cutout looks worst in some area [not all], what is the correct arguments for 4K settings to make full use of all those extra pixel information ?

Can you help to modify the 4k arguments presented here to make them better ?

![git](https://user-images.githubusercontent.com/46036208/128597681-d2c8e568-b1cc-4b3b-b37c-49555539c0b1.png)

**Comment by PeterL1n** [comment]
Feel free to use whatever argument that suits your footage. They trade-off between speed and quality.

**Comment by BracerJack** [comment]
What if I don't care about speed and I want full on quality for the 4K footage ?
What can I change in the argument to make it focus solely on quality ?
Thanks :D
