### ISSUE TITLE
Unreal Engine?

### ISSUE THREAD

**Issue by turkodamian** [PeterL1n/BackgroundMattingV2#146]
Is it possible to use it with Unreal Engine 4 or Unreal Engine 5 in real time? what is the recommended workflow?
Thanks

**Comment by PeterL1n** [comment]
Not sure. This is outside of my domain.

**Comment by Tetsujinfr** [comment]
@turkodamian you mean to use it on cgi frame fully rendered by the Unreal engine? or to use it on a real video/webcam stream, which is then passed onto the Unreal engine?
Both cases should be possible, but you would have to build your own plugin I think (c++), and wrap it to the python code here. Some work certainly...
