### ISSUE TITLE
Limitations on the aspect ratio

### ISSUE THREAD

**Issue by igorcosta** [PeterL1n/BackgroundMattingV2#148]
I'm trying to understand a bit how the model works. I have one, question:

Why there's a limitation in terms of the aspect ratio for example Source differs from the background. For instance, if I generate a new background image based on the source dimensions, I'm still not able to remove the background. 

Looking into the code, this is a required aspect. Can you explain a bit, just for my sake of understanding why?

**Comment by PeterL1n** [comment]
You suppose to provide the actual background of the source (pre-captured without the subject in frame), not the target background.
