### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'PATH_TO_CHECKPOINT'

### ISSUE THREAD

**Issue by kvibert** [PeterL1n/BackgroundMattingV2#153]
run inference_webcam.py 
show FileNotFoundError: [Errno 2] No such file or directory: 'PATH_TO_CHECKPOINT'

**Comment by 143396** [comment]
You have to put the path of the model file in the --model-checkpoint flag. All of the model files are available at https://drive.google.com/drive/folders/1cbetlrKREitIgjnIikG1HdM4x72FtgBh
