### ISSUE TITLE
Doubts about evaluation on different datasets

### ISSUE THREAD

**Issue by caihaunqai** [PeterL1n/BackgroundMattingV2#165]
Hello, thank you for your excellent work. We know that our model is trained in a order on multiple datasets.  Do you use the same operation， which means training on multiple datasets and evaluating on one certain dataset,  when comparing with other methods on a certain dataset?   I wonder if other methods in  quantitative evaluation in the paper's Table 1  also use multiple datasets for training？ Thank you~

**Comment by PeterL1n** [comment]
Evaluation is all done on the final model, which is trained on VideoMatte, PhotoMatte, and Distinctions.

**Comment by caihaunqai** [comment]
> Evaluation is all done on the final model, which is trained on VideoMatte, PhotoMatte, and Distinctions.

Thank you for your reply. Are other methods in paper's Table 1 also trained on VideoMatte, PhotoMatte, and Distinctions?  If so, do they also train in order or use their papers' training methods?

**Comment by PeterL1n** [comment]
We retrained BGM on the three datasets and called it BGM adapt. Other methods are not if I remembered it correctly.

**Comment by caihaunqai** [comment]
> Owner
> ### [<img alt="@PeterL1n" width="20" height="20" src="https://avatars.githubusercontent.com/u/7651753?s=60&amp;u=72ad6660f7f9592e4718393f4e3f97d50d0615ef&amp;v=4">](/PeterL1n) ** [PeterL1n](/PeterL1n) ** commented [15分钟前](#issuecomment-986561590)

Thank you. Yes, I think other methods may be not trained in the same way, because other methods require trimap or other input, and  VideoMatte, PhotoMatte do not provide trimaps.
