### ISSUE TITLE
Question regarding freezing model weights

### ISSUE THREAD

**Issue by 95maddycode** [PeterL1n/BackgroundMattingV2#173]
Hello there,

Thank you very much for your lovely work. I have a small question regarding freezing weights.

In the paper it is stated that the complete model (MattingRefine) is trained with freezed backbone weights. However, if I look in the code, I cannot see where this freezing of the model backbone weights is actually happening.

How does the model know that the backbone weights are freezed during the training of matting refine? 
And where in the code is this happening? 

Kind regards

**Comment by PeterL1n** [comment]
I don't remember saying the backbone was freezes during training.

**Comment by 95maddycode** [comment]
Oops, you are right. I was assuming that the base was freezed when training the matting refine model, to keep it on the optimal ("converged") level. My apologies.
