### ISSUE TITLE
Dataset release schedule

### ISSUE THREAD

**Issue by AmberCheng** [PeterL1n/BackgroundMattingV2#2]
Hi, thanks for your awesome work! 
I recently do some researches about human body segmentation. I wonder do you have a schedule to provide the dataset which I am really interested in?

**Comment by PeterL1n** [comment]
We are figuring out the details and hope to release them soon. Currently, we can't provide a fixed time schedule.

**Comment by David-water** [comment]
Hello,Congratulations for your work!  
I wonder when the dataset will be released? Will it be released this year?

**Comment by PeterL1n** [comment]
It is hard to say. We are working on it.

**Comment by PeterL1n** [comment]
PhotoMatte85 dataset is now available for download.

**Comment by AmberCheng** [comment]
emmm...why the photo85 only have 84? Did you miss one photo?

**Comment by PeterL1n** [comment]
@AmberCheng Fixed. We reuploaded the zip with 85 samples now.

**Comment by 99991** [comment]
Just to make sure, the README says: `This work is licensed under the MIT License.` This includes the PhotoMatte85 dataset as well?

I noticed that for two images, a few pixels at the top-left are matted incorrectly.

![bug](https://user-images.githubusercontent.com/18725165/106856079-43aa8480-66be-11eb-95e2-1e355ae3533e.png)

I guess the images were obtained via greenscreen matting and the greenscreen was hanging too low. It probably does not matter much, but here is some code to fix those images.

```python3
from PIL import Image
import numpy as np

for filename in ["0051115Q_000001_0049.png", "0051115Q_000001_0085.png"]:
    image = np.array(Image.open(filename))
    print(image.dtype)

    # zero out top 100 rows of image to fix bad alpha matte
    print(image.shape)
    image[:100] = 0

    Image.fromarray(image).save(filename)
```

**Comment by Julyliying** [comment]
> PhotoMatte85 dataset is now available for download.

When the VideoMatte240K dataset will be released?Thank you.

**Comment by PeterL1n** [comment]
We finally finalized the licensing of the VideoMatte240K dataset. Currently planning to release it on April 12.

**Comment by PeterL1n** [comment]
Actually there are still some delay. Likely to be in this week or next.

**Comment by PeterL1n** [comment]
Dataset is released. Checkout the README of the repo.
