### ISSUE TITLE
The link for the trained model is broken

### ISSUE THREAD

**Issue by ohkwon718** [PeterL1n/BackgroundMattingV2#204]
![image](https://github.com/PeterL1n/BackgroundMattingV2/assets/19196641/c5f8ea03-1f85-46ad-a65c-886b4314ca8b)

Hi. The Google Drive link seems broken.
Can you fix the link or re-upload the weight?
Thank you.

**Comment by PeterL1n** [comment]
I can't find a backup for the weights...
Anyone else has the weights please share it back.

**Comment by ohkwon718** [comment]
Do you think someone can manage to train the model and reproduce a similar result by himself?
According to the description, the training seems to require "train_base.pth" and "train_refine.pth" files.

"Configure data_path.pth to point to your dataset. The original paper uses train_base.pth to train only the base model till convergence then use train_refine.pth to train the entire network end-to-end. More details are specified in the paper."

**Comment by PeterL1n** [comment]
The link is restored :)

**Comment by ohkwon718** [comment]
Thank you very much :)
