### ISSUE TITLE
Running on MacOS (no Nvidia GPU)

### ISSUE THREAD

**Issue by adeelabbas** [PeterL1n/BackgroundMattingV2#31]
Hi,
When I run the `inference_video.py`, I get following error:

```
AssertionError: Torch not compiled with CUDA enabled
```

I looked up online but there does not seem a way to get Cuda to run on my Macbook (which is 2020 model and pretty high end unfortunately). Any way, this can be run on MacOS?

**Comment by PeterL1n** [comment]
Add `--device cpu` argument to use cpu inference.

**Comment by adeelabbas** [comment]
Thanks
