### ISSUE TITLE
Cannot deal with background change

### ISSUE THREAD

**Issue by YanHuiGUO** [PeterL1n/BackgroundMattingV2#32]
I just take a picture using my phone to get a background. And at the same position, I take another picture including my upper body. The demo you provided cannot produce a good result. I think the background just has small changes which are very common in real applications and the background is not complicated. Hope you can make it more applicable :）

**Comment by PeterL1n** [comment]
It is designed for matching backgrounds. For the best result use a tripod. For small motion handheld, you can preprocess the image for alignment and then pass it through the model. `inference-image.py` has `--preprocess-alignment` argument.
