### ISSUE TITLE
--model-type mattingrefine

### ISSUE THREAD

**Issue by adeelabbas** [PeterL1n/BackgroundMattingV2#33]
When I run `inference_video` with `--model-type mattingrefine` parameter, does it run `mattingbase` first and then refinement? Wondering if I need to run two passes myself or if the script takes care of this.

**Comment by PeterL1n** [comment]
You don't need to run two passes. The script takes care of it itself.

If you look into `model/model.py`,  `MattingRefine` is a class extending `MattingBase` and with the refinement module. It is just some internal naming.

**Comment by adeelabbas** [comment]
Cool - thanks!
