### ISSUE TITLE
Is fps in paper including with the pre-process/post-process time or not?

### ISSUE THREAD

**Issue by xiuyangleiasp** [PeterL1n/BackgroundMattingV2#37]

**Comment by PeterL1n** [comment]
No. The fps reported is generated using the `inference_speed_test.py` script. As you can see, it does not do pre/post processing. It is assuming the image tensors are already on the GPU so it does not count the data transferring but only the model passthrough rate. We have found that this has been used for many other papers for measuring the speed. The assumption is that the data transfer can be processed in a separate thread concurrently, but our code does not provide that level of engineering.

**Comment by xiuyangleiasp** [comment]
Thanks.
