### ISSUE TITLE
Does the model only support humans

### ISSUE THREAD

**Issue by SodrSnne** [PeterL1n/BackgroundMattingV2#4]
What do I do if I want to separate the vehicle from the background

**Comment by PeterL1n** [comment]
Our model is only trained for human matting. You may try it with cars but I suspect the result won't be great. If you can find a car matting dataset, you can train a model yourself after we release our training code.

Alternatively, matting for cars doesn't usually require details like human hairs so you could try using a semantic segmentation network. Alternatively, if you really want high-quality matting, maybe try the classical trimap-based methods, such as [A Closed Form Solution to Natural Image Matting](https://people.csail.mit.edu/alevin/papers/Matting-Levin-Lischinski-Weiss-CVPR06.pdf) and its [implementation](https://github.com/MarcoForte/closed-form-matting). It doesn't need any training and works on any objects but requires a trimap. I hope this helps.

**Comment by SodrSnne** [comment]
Thank you for your answers and recommendations
I accidentally found your code and tried to run it. The result is great and I admire it
Because I'm learning about license plates and car detection recently, car segmentation is just one of my thoughts. After your guidance, I will learn the content of semantic segmentation, but I still look forward to your training code
Thanks again for your answer
