### ISSUE TITLE
How can the demo run with CPU？

### ISSUE THREAD

**Issue by dalunzi-dreamers** [PeterL1n/BackgroundMattingV2#42]
hi，my MacBook pro's OS is Big Sur, no matching  CUDA Drivers.
when I run the demo inference_webcam.py , error like this:

line 137, in <module>
    model = model.cuda().eval()
AssertionError: Torch not compiled with CUDA enabled

How can the demo run with CPU？
thanks.

**Comment by PeterL1n** [comment]
You can change every `.cuda()` in the code to `.cpu()`.
But I think the demo will be very slow without a GPU.

**Comment by dalunzi-dreamers** [comment]
1.command：
python3 inference_webcam.py  --model-type mattingrefine  --model-backbone resnet50  --model-checkpoint  /Users/mac/Documents/PythonApp/BackgroundMattingV2-master/PyTorch_pth/pytorch_resnet101.pth  --resolution 1280 720

2.changed：
model = model.cpu()
model.load_state_dict(torch.load(args.model_checkpoint , map_location='cpu' ), strict=False)

def cv2_frame_to_cuda(frame):
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    return ToTensor()(Image.fromarray(frame)).unsqueeze_(0).cpu()

3.It can capture the camera pictures ，when I press ‘b’，procedure is abort
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])

I just want run this demo ,  how can i make it works?

**Comment by PeterL1n** [comment]
```
model = model.cpu().eval()
```

You forgot `.eval()`.

**Comment by dalunzi-dreamers** [comment]
Wow, Bravo.
Without GPU , fps slow down to 1  but it works.
bgr was removed, also had some noise and shadows .
I will run it with GPU recently.
Thank u !
