### ISSUE TITLE
--output-format image_sequences not working on the colab

### ISSUE THREAD

**Issue by navalguijo** [PeterL1n/BackgroundMattingV2#44]
Hi there,

I just made my first test and I'm very pleased with a 4K video.
but when I add the --output-format image_sequences I get this error
  File "<ipython-input-10-9b84f4f10957>", line 2
    --output-format image_secuences
    ^
IndentationError: unexpected indent

I would love to have some sequence as export...
Also...is there a posibility to use another type of file as input? I would love to have my image sequence as input so I can use it for real with some cinema camera files...

Thanx a lot!!

**Comment by PeterL1n** [comment]
I don't know what was your old problem, but I tried and it worked for me.
Go to the Colab video inference demo and replace the last cell with the following. You will get image sequence output
```
!python inference_video.py \
        --model-type mattingrefine \
        --model-backbone resnet50 \
        --model-backbone-scale 0.25 \
        --model-refine-mode sampling \
        --model-refine-sample-pixels 80000 \
        --model-checkpoint "/content/model.pth" \
        --video-src "/content/src.mp4" \
        --video-bgr "/content/bgr.png" \
        --output-dir "/content/output/" \
        --output-type com fgr pha err ref \
        --output-format image_sequences
```


You can definitely do image-in and image-out. `inference_images.py` does that but it requires you to copy the background image for every corresponding frame.

You can always write your own inference script to have a more efficient conversion that takes in and outputs whatever format or codec, but you will have to do the programming yourself.
