### ISSUE TITLE
very pool result on MACOS with CPU

### ISSUE THREAD

**Issue by albertyou2** [PeterL1n/BackgroundMattingV2#45]
MACOS : 10.15.5
PYTHON :3.6.4
torch      :1.7.0         (pip install ,not conda )
tensorflow : 1.14.0

hi @PeterL1n
I have tested   inference_images.py by using this command : 
python inference_images.py --model-type mattingrefine --model-backbone resnet101 --model-backbone-scale 0.25 --model-refine-mode sampling --model-refine-sample-pixels 80000 --model-checkpoint ./model/data/pytorch_resnet101.pth --images-src ./images/data --images-bgr ./images/bgr --output-dir ./images/output --output-type com fgr pha err ref --device cpu 

I did not change any code of this file .
I downloaded 'pytorch_resnet101.pth' model and use it for testing.  

It works , but the result  is very pool .
This is my src image :

![1](https://user-images.githubusercontent.com/11494761/104404849-98168480-5596-11eb-9d75-c839d46a6033.jpg)
 
and this is my  bgr image : 
![2](https://user-images.githubusercontent.com/11494761/104404882-ac5a8180-5596-11eb-84f3-acb27a70dd5d.jpg)

These are outputs :

com :
![1](https://user-images.githubusercontent.com/11494761/104404974-e4fa5b00-5596-11eb-9380-7eca8ced9469.png)

fgr:
![1](https://user-images.githubusercontent.com/11494761/104404991-ecb9ff80-5596-11eb-82ee-4789a71e3c9e.jpg)

ref : 
![1](https://user-images.githubusercontent.com/11494761/104405028-fd6a7580-5596-11eb-9bb6-6c9dea8e4d0b.jpg)

err:
![1](https://user-images.githubusercontent.com/11494761/104405131-39053f80-5597-11eb-905b-662fa3df8983.jpg)

Do you have any idea about this problem? 
thank you !

**Comment by PeterL1n** [comment]
You suppose to provide a pre-captured background of the input image without the subject. It is not asking you to provide a background that you want to replace it with.

**Comment by albertyou2** [comment]
OK ,It 's My fault !
Thank you very much !
