### ISSUE TITLE
How to synthesize a new background?

### ISSUE THREAD

**Issue by WIKI2020** [PeterL1n/BackgroundMattingV2#5]
How to synthesize a new background?

**Comment by PeterL1n** [comment]
After the model generated alpha `pha` and foreground `fgr`, you can compose it onto a new background `bgr` through: 
```
com = pha * fgr + (1 - pha) * bgr
```

**Comment by WIKI2020** [comment]
It is better to change the file directly to synthesize new background instead of green screen, which is more convenient to readers

**Comment by PeterL1n** [comment]
This can certainly be implemented as an additional feature for the conversion script. I will take a look soon.

**Comment by adeelabbas** [comment]
+1 to this feature

**Comment by andreyryabtsev** [comment]
Added an optional flag `--video-target-bgr` to `inference_video.py` that will change the `com` output to be onto the video at the specified path, instead of plain green color ([commit](https://github.com/PeterL1n/BackgroundMattingV2/commit/9c9b9592e8fa7f60af4a00a54507797e96b0ac71))

**Comment by imerse** [comment]
Excellent work! Excuse me, if I use a single background for synthesis, there is no problem, and the matting is normal, but if I use a complex background for synthesis, there will be such problematic edges. What should I do in this situation? Has anyone encountered it?

![image](https://user-images.githubusercontent.com/8415005/107339614-d6508680-6af7-11eb-84dd-91a1198025fd.png)
![image](https://user-images.githubusercontent.com/8415005/107339671-e8322980-6af7-11eb-9690-9659f53fb92f.png)
![image](https://user-images.githubusercontent.com/8415005/107339745-013ada80-6af8-11eb-86a0-8aba350c8f37.png)
