### ISSUE TITLE
the predicted results of crop patch will have residual zigzag in refine stage

### ISSUE THREAD

**Issue by JuneXia** [PeterL1n/BackgroundMattingV2#56]
Hi, Your paper is excellent, and many thanks for the inference code you contributed. I am a student majoring in CS, and I am trying to reproduce your paper. 
I found that **the predicted results of crop patch will have residual zigzag in refine stage**. Have you ever encountered a similar situation and how to solve it? 
Looking forward to your reply.

**Comment by PeterL1n** [comment]
Can you provide an image?

**Comment by JuneXia** [comment]
Below is our predicted results in refine stage, that's the part of a body's shoulder, please pay attention to the edges of the image.
![alpha_pred_rf_v0105_issue](https://user-images.githubusercontent.com/7473062/105964467-30475a00-60bd-11eb-8045-4d7b0f4d8b55.png)

**Comment by PeterL1n** [comment]
I think our model does have this artifact sometimes. It's not your problem.

**Comment by JuneXia** [comment]
> I think our model does have this artifact sometimes. It's not your problem.

think you for your reply. 
I tried to refine the whole image directly instead of taking patch, so as to eliminate the residual zigzag, but the hair area could not be refined finely.
