### ISSUE TITLE
issue after convert to onnx and openvino

### ISSUE THREAD

**Issue by bianxg** [PeterL1n/BackgroundMattingV2#57]
Please check where is problem. Thanks
1 export onnx model
python export_onnx.py \
        --model-type mattingbase \
        --model-checkpoint "./pytorch_mobilenetv2.pth" \
        --model-backbone mobilenetv2 \
        --model-backbone-scale 0.25 \
        --model-refine-mode sampling \
        --model-refine-sample-pixels 80000 \
        --model-refine-patch-crop-method roi_align \
        --model-refine-patch-replace-method scatter_element \
        --onnx-opset-version 11 \
        --onnx-constant-folding \
        --precision float32 \
        --output "model.onnx" \
        --validate

2 model optimize using openvino
python /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo_onnx.py --input_model onnx_mobilenetv2_hd.onnx --input_shape [1,3,1080,1920],[1,3,1080,1920] --input src,bgr 

3 infer using openvino

The result is as shown:
![matting](https://user-images.githubusercontent.com/3364079/106112468-42da9580-6188-11eb-9778-ee7c83d601b9.png)

**Comment by bianxg** [comment]
have fixed it. Please refer:
https://github.com/kingpeter2015/libovmatting

**Comment by PeterL1n** [comment]
Nice. What was the problem.

**Comment by bianxg** [comment]
The input data format was wrong. 
After retesting, I found that the performance has doubled after using openvino(using CPU).  Can improve more?

**Comment by PeterL1n** [comment]
Awesome. I am not sure if the performance can improve more unless you want to go into redesigning the model architecture and retraining.
