### ISSUE TITLE
What's the difference between MobileNetV2 and ResNet50?

### ISSUE THREAD

**Issue by cloudweather** [PeterL1n/BackgroundMattingV2#6]
Are there any pros and cons or MobileNetV2 is just better than ResNet50?

**Comment by PeterL1n** [comment]
MobileNetV2 is designed to be light-weight. It is much smaller and faster. However, the resulting matting is not as robust as ResNet50, as shown in our research paper. We further experimented with ResNet101 (even more layers than ResNet50) but do not see improvement, so ResNet50 is the best quality you can get. For building your application, you can trade-off quality and speed with MobileNetV2 and ResNet50 depending on your need. A more detailed comparison of FPS and quality is in our paper!
