### ISSUE TITLE
inference_images.py  has no results

### ISSUE THREAD

**Issue by yangxulin** [PeterL1n/BackgroundMattingV2#62]
When I run file inference_video.py , I get the result I want,but when I run file inference_images.py, I get the following result:

(bgmatt) F:\BackgroundMattingV2-master>python inference_images.py --model-type mattingrefine --model-backbone resnet50 --model-refine-sample-pixels 320_000 --model-checkpoint ./model/PyTorch/pytorch_resnet50.pth --images-src ./input/img/0.png --images-bgr ./input/bgr/0.png --output-dir ./output --output-type com fgr pha
Directory ./output already exists. Override? [Y/N]: y
0it [00:00, ?it/s]

There was no error, but there was no result.The images used in the test were downloaded from the Google disk you provided.
Thank you for creating an excellent work, and hope you can solve my problem

**Comment by PeterL1n** [comment]
Sorry for the confusion, the images-src and images-bgr argument expects a folder instead of the file, so put the image into a folder and provide the folder instead. The script will process all the images under that folder, and it expects source and background image files have the same name.

**Comment by yangxulin** [comment]
> 很抱歉造成混淆，images-src和images-bgr参数期望使用文件夹而不是文件，因此将图像放入文件夹并提供该文件夹。该脚本将处理该文件夹下的所有图像，并且期望源图像文件和背景图像文件具有相同的名称。
> 
> 例如
> 
> ```
> .../src/001.png
> .../bgr/001.png
> ```

Thank you very much. I've solved my problem
