### ISSUE TITLE
file not found: archive/constants.pkl

### ISSUE THREAD

**Issue by ecsplendid** [PeterL1n/BackgroundMattingV2#65]
Great work on this folks!

I am trying to run this code using your `pytorch_resnet101.pth`;

![image](https://user-images.githubusercontent.com/6911390/109937895-4ef5cd80-7cc7-11eb-8fdc-44858f126b84.png)

And get 
![image](https://user-images.githubusercontent.com/6911390/109937917-561cdb80-7cc7-11eb-85fa-39dda234030d.png)

It's looking for an `archive/constants.pkl`

Can you help?

**Comment by ecsplendid** [comment]
Some more info here which seems relevant -- 

https://github.com/pytorch/pytorch/issues/47917

![image](https://user-images.githubusercontent.com/6911390/109939848-5d44e900-7cc9-11eb-9e5e-1fad0e2e3e97.png)


Is it possible you folks used torch.save and were supposed to use something else? Perhaps this model you published is no longer a torchscript model?

**Comment by PeterL1n** [comment]
The error is in line:
```
torch.jit.load('pytorch_resnet101.pth')
```
If you want to use TorchScript, you need to load the torchscript pth weights.
If you want to use PyTorch code as exactly shown in the screenshot, use the pytorch pth weights.
You are mixing the two.
