### ISSUE TITLE
Doesn't work on any of my videos

### ISSUE THREAD

**Issue by ecsplendid** [PeterL1n/BackgroundMattingV2#66]
When I use your src.mp4 i.e. 

```
!gdown https://drive.google.com/uc?id=1tCEk8FE3WGrr49cdL8qMCqHptMCAtHRU -O /content/src.mp4 -q
```

It works great

![image](https://user-images.githubusercontent.com/6911390/109963042-d9e4c100-7ce3-11eb-9e78-6e30ceaa0874.png)

However when I use one of my videos (h264 1080) it doesn't work at all

This is the alpha:

![image](https://user-images.githubusercontent.com/6911390/109963117-eff28180-7ce3-11eb-8104-b725d9980566.png)

From this input: 

![image](https://user-images.githubusercontent.com/6911390/109963171-00a2f780-7ce4-11eb-9b48-81234bac6eb4.png)

From running this command (notice I also get an error message but video still produced)

![image](https://user-images.githubusercontent.com/6911390/109963241-17e1e500-7ce4-11eb-96b5-472f26394789.png)

**Comment by ecsplendid** [comment]
Here is the video I made to reproduce the problem

```
!gdown https://drive.google.com/uc?id=1q2MzIcsXIknxzKJSms9VxU2icVz3YV8R -O /content/tim.mp4 -q
```

I can reproduce it on your Google Collab too so it's not my machine/environment

**Comment by PeterL1n** [comment]
Our model is called Background Matting, which requires you to supply an additional background capture without the subject. You didn't seem to provide a correctly pre-captured background through the --video-bgr argument. You are still using the demo bgr.png which is definitely not correct.

**Comment by ecsplendid** [comment]
Oh! My bad sorry I feel dumb now -- I should have read your paper before trying this. 

Do you think it would be possible to use your refiner idea on top of a standard salient object segmentation model and skip the need to have the background photo? Does it confer a huge improvement?

**Comment by PeterL1n** [comment]
You can definitely adopt the refiner idea to segmentation networks. This requires you to experiment and train your own network. It will definitely allow processing higher resolution images with much lower resources than passing through a standard conv-net, but it may not able to recover all the hair details without a background.

**Comment by fangchao** [comment]
> Our model is called Background Matting, which requires you to supply an additional background capture without the subject. You didn't seem to provide a correctly pre-captured background through the --video-bgr argument. You are still using the demo bgr.png which is definitely not correct.

Hi, @PeterL1n .I have supply an additional background capture without the subject by my mobile phone, but it is still not work.
Is there anything else I need to modify or supply?

`"inference_video.sh" 17L, 623C                                                                                                              1,1           All
python3 inference_video.py \
     --model-type mattingbase \
     --model-backbone resnet50 \
     --model-backbone-scale 0.25 \
     --model-refine-mode sampling \
     --model-refine-sample-pixels 80000 \
     --model-checkpoint ./PyTorch/pytorch_resnet50.pth \
     --video-src "./1615342262545425.mp4" \
     --video-bgr "./WechatIMG125.jpeg" \
     --video-resize 1920 1080 \
     --output-dir "./test" \
     --output-type com fgr pha err`

This is my video-gbr.
![WechatIMG125](https://user-images.githubusercontent.com/3609495/110571186-2885d580-8192-11eb-905d-84ecd920b33e.jpeg)

**Comment by PeterL1n** [comment]
Change model-type to mattingrefine.

You better provide video frame, background image, and model output to let me debug.

**Comment by swelcker** [comment]
I think the background needs to have the same size/scale as the input video frame size
