### ISSUE TITLE
about validation dataset PhotoMatte85

### ISSUE THREAD

**Issue by LuoYingzhao** [PeterL1n/BackgroundMattingV2#69]
Thanks for your excellent work for image matting. 
I find that there are no groundtruth alpha for 85 pictures in validation dataset PhotoMatte85 to do some objective test. So, could you please share the gt alpha for the PhotoMatte85?

**Comment by PeterL1n** [comment]
All 85 images are RGBA png. Ground truth alpha is in the alpha channel.
