### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by decajcd** [PeterL1n/BackgroundMattingV2#71]
In VideoMatte240K dataset, why the mobile phone appeared in videos is  green?

**Comment by PeterL1n** [comment]
What are you referring to?

**Comment by decajcd** [comment]
![image](https://user-images.githubusercontent.com/22631997/110910230-03d55d80-834c-11eb-94a0-73ce988d4804.png)
like this

**Comment by PeterL1n** [comment]
You are not supposed to use that. That is not in the VideoMatte240K dataset for training our model. The link in this repo simply refers to storyblocks.com but not the exact search page. If you want to download and create your own dataset, you need to filter out only the human green screen footage.

**Comment by decajcd** [comment]
o懂啦，谢谢
