### ISSUE TITLE
Real-time background replacement in a web browser

### ISSUE THREAD

**Issue by benbro** [PeterL1n/BackgroundMattingV2#72]
Is it possible to use it in a browser for real-time video background replacement? Are there instructions?
Something like:
https://ai.googleblog.com/2020/10/background-features-in-google-meet.html

**Comment by swelcker** [comment]
you basically just use a virtual (fake) webcam in the browser app, the background replacement reads a real webcam and feeds the virtual one, all outside of the browser task/thread/process

**Comment by benbro** [comment]
It will be a better UX to be able to do it in a web app without installing a separate virtual webcam app.
Is it possible to use [ONNX.js](https://github.com/microsoft/onnxjs), [tfjs](https://github.com/tensorflow/tfjs) or [mediapipe](https://github.com/google/mediapipe) to run the matting in the browser?

**Comment by PeterL1n** [comment]
I have attempted to try tfjs, but it is very slow and not usable. ONNX.js straight up can't be converted.

**Comment by benbro** [comment]
@PeterL1n can you please share your tfjs code and model? The Google Meet model is fast in the browser so we could probably make BackgroundMattingV2 model fast too.
