### ISSUE TITLE
background image required?

### ISSUE THREAD

**Issue by carter54** [PeterL1n/BackgroundMattingV2#78]
Hi~ thx for this excellent work. 
I noticed that a background image is used as input for both base and refine network. 
Did you try to train models without this background image? As in real case, both image and video might not provide a background image when you want to do the matting.

**Comment by nostayup** [comment]
I am also very curious about this question

**Comment by PeterL1n** [comment]
Training it without the background currently doesn't generate very good results. It is still under our further research. Currently, it appears that background information really helps matting on hair details, etc.

**Comment by aiminsu** [comment]
Hey, Thanks for your work! I was wondering if it is mandatory to do matting with a background image, which shares the same background with the source image,  even during the inference time?

**Comment by PeterL1n** [comment]
@aiminsu Yes for this work, it is mandatory even during the inference time.
