### ISSUE TITLE
How to use the “/model" script？

### ISSUE THREAD

**Issue by Joevaen** [PeterL1n/BackgroundMattingV2#8]
I dont know how to follow the usage and documents, like below：
`import torch
from model import MattingRefine

device = torch.device('cuda')
precision = torch.float32

model = MattingRefine(backbone='mobilenetv2',
                      backbone_scale=0.25,
                      refine_mode='sampling',
                      refine_sample_pixels=80_000)

model.load_state_dict(torch.load('PATH_TO_CHECKPOINT.pth'))
model = model.eval().to(precision).to(device)

src = torch.rand(1, 3, 1080, 1920).to(precision).to(device)
bgr = torch.rand(1, 3, 1080, 1920).to(precision).to(device)

with torch.no_grad():
    pha, fgr = model(src, bgr)[:2]`

where this code read my own image？Are the `src = torch.rand(1, 3, 1080, 1920).to(precision).to(device)
bgr = torch.rand(1, 3, 1080, 1920).to(precision).to(device)`are only an example？I don't understand. 
So I use this `inference_images.py` to infer my image. I sort my data and pretrained model like this： 
![2020-12-19 01-54-25屏幕截图](https://user-images.githubusercontent.com/46133615/102645343-49dfb280-419d-11eb-9e96-f9d8213c5b7e.png)
And add args like this：
`--model-type
mattingrefine
--model-backbone
resnet50
--model-checkpoint
/home/user/BackgroundMattingV2/A_matting/model/PyTorch/pytorch_resnet50.pth
--images-src
/home/user/BackgroundMattingV2/A_matting/input/1384624442.jpg
--images-bgr
/home/user/BackgroundMattingV2/A_matting/input/timg.jpeg
--output-dir
/home/user/BackgroundMattingV2/A_matting/output/out.jpg
--output-types
com
-y`
It didn't work and error reported like `0it [00:00, ?it/s]` and nothing export out.
Could you help me please？
Thanks！
Best,
Joevaen.

**Comment by andreyryabtsev** [comment]
Hi @Joevaen 
So the code sample you showed is for if you wanted to write your own code using our model. You would find your own ways to load images in, so we just use random inputs as an example.

If (as it sounds) you are just trying to run inference on images, then I think your biggest issue is that all arguments should be directories (of inputs or outputs) - not individual images. Also, all extensions should be ".jpg" or ".png".

So you could move your "1384624442.jpg" and "timg.jpeg" into separate "input source images" and "input backgrounds" directories, and name the same thing (ending in ".jpg") so they match - and then supply those directories to the script.

**Comment by Joevaen** [comment]
I got that, thank you andrey! I will try.

**Comment by Joevaen** [comment]
> Hi @Joevaen
> So the code sample you showed is for if you wanted to write your own code using our model. You would find your own ways to load images in, so we just use random inputs as an example.
> 
> If (as it sounds) you are just trying to run inference on images, then I think your biggest issue is that all arguments should be directories (of inputs or outputs) - not individual images. Also, all extensions should be ".jpg" or ".png".
> 
> So you could move your "1384624442.jpg" and "timg.jpeg" into separate "input source images" and "input backgrounds" directories, and name them the same thing (ending in ".jpg") so they match - and then supply those directories to the script.

I followed your advice but error was encountered like below：
`/home/qiao/anaconda3/bin/python /home/qiao/PythonProjects/BackgroundMattingV2/inference_images.py --model-type mattingrefine --model-backbone mobilenetv2 --model-checkpoint /home/qiao/PythonProjects/BackgroundMattingV2/A_matting/model_pre/PyTorch/pytorch_mobilenetv2.pth --images-src /home/qiao/PythonProjects/BackgroundMattingV2/A_matting/input/input_source_images --images-bgr /home/qiao/PythonProjects/BackgroundMattingV2/A_matting/input/input_backgrounds --output-dir /home/qiao/文档/A_matting/output --output-types com -y
  0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/qiao/PythonProjects/BackgroundMattingV2/inference_images.py", line 120, in <module>
    for i, (src, bgr) in enumerate(tqdm(dataloader)):
  File "/home/qiao/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1165, in __iter__
    for obj in iterable:
  File "/home/qiao/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/qiao/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/qiao/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/qiao/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/qiao/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/qiao/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qiao/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qiao/PythonProjects/BackgroundMattingV2/dataset/zip.py", line 19, in __getitem__
    x = self.transforms(*x)
  File "/home/qiao/PythonProjects/BackgroundMattingV2/dataset/augmentation.py", line 21, in __call__
    x = transform(*x)
  File "/home/qiao/PythonProjects/BackgroundMattingV2/dataset/augmentation.py", line 30, in __call__
    return [self.transforms(xi) for xi in x]
  File "/home/qiao/PythonProjects/BackgroundMattingV2/dataset/augmentation.py", line 30, in <listcomp>
    return [self.transforms(xi) for xi in x]
TypeError: ToTensor() takes no arguments`
Why this happened？Should I fix the bgr and src with same  shape before input them？

**Comment by arthurmchr** [comment]
@Joevaen In file `inference_images.py`, on line 95, replace `A.PairApply(T.ToTensor)` by `A.PairApply(T.ToTensor())`

**Comment by arthurmchr** [comment]
@Joevaen In file inference_images.py, on line 95, replace A.PairApply(T.ToTensor) by A.PairApply(T.ToTensor())

**Comment by PeterL1n** [comment]
@arthurmchr Thanks for helping us finding a bug.
