### ISSUE TITLE
For the inference time test:  

### ISSUE THREAD

**Issue by zhanghongyong123456** [PeterL1n/BackgroundMattingV2#81]
For the inference time test:
No matter which model I run in inference_images.py (MobileNetV2 resnet50 resnet101), I always get an FPS of 2it/s. In inference_speed_test.py, I get an FPS of 40 it/s for model resnet50, 33it/s for model resnet101, and 75 it/s for MobileNetV2.I don't know what causes this,
![inference_images py （random model）fps](https://user-images.githubusercontent.com/48466610/113236420-64b2de80-92d7-11eb-92a5-d3d5e928cfcd.png)
![inference_speed_test py（mobilenetv2） fps](https://user-images.githubusercontent.com/48466610/113236426-65e40b80-92d7-11eb-8e5a-24573af7d651.png)

**Comment by PeterL1n** [comment]
The inference script won't get you the full performance, because there is additional image encoding/decoding that is not utilizing hardware acceleration/parallelism. Please understand that this is only an academic paper proving the point that the neural model can achieve fast speed, but we don't provide another software engineer that makes it production real-time.

**Comment by PeterL1n** [comment]
I think 2it/s is actually very slow. I don't know what other factors are causing it but I usually expect around 10fps normally.

**Comment by zhanghongyong123456** [comment]
> 推理脚本无法获得完整的性能，因为还有其他图像编码/解码没有利用硬件加速/并行性。请理解，这只是一篇学术论文，证明了神经模型可以实现更快的速度，但是我们没有提供其他软件工程师来使它实时生产。

Thank you very much for your prompt reply. I always thought that my own configuration problem caused such a result. Next, I will study how to load data faster。Thanks again for your reply and answer

**Comment by zhanghongyong123456** [comment]
> The inference script won't get you the full performance, because there is additional image encoding/decoding that is not utilizing hardware acceleration/parallelism. Please understand that this is only an academic paper proving the point that the neural model can achieve fast speed, but we don't provide another software engineer that makes it production real-time.

Thank you very much for your prompt reply. I always thought there was something wrong with my own configuration, but now I know that the speed was slowed down by other reasons rather than the model itself. Next, I will study how to accelerate data processing and improve the speed.Thanks again for your reply and answer
