### ISSUE TITLE
about run export_torchscript.py   

### ISSUE THREAD

**Issue by zhanghongyong123456** [PeterL1n/BackgroundMattingV2#82]
For the export_torchscript.py run, this problem arises.Not very clear code specific implementation, so some confusion
![001](https://user-images.githubusercontent.com/48466610/113717530-49ecc980-971e-11eb-8bd6-e20dd7e32872.png)

**Comment by PeterL1n** [comment]
There was a bug. Pull the master branch again. Should work now.

**Comment by zhanghongyong123456** [comment]
> There was a bug. Pull the master branch again. Should work now.

Yes, she has started to work. Thank you for your prompt reply
