### ISSUE TITLE
background images

### ISSUE THREAD

**Issue by PROMISELVKR** [PeterL1n/BackgroundMattingV2#84]
hello, I want to train my own model by using dataset:photomatte85,but when I modify the data_path.py file,I find there is a 'backgrounds' option that I should provide,I don't know what kind of background-images I should provide to the code,and in the photomatte85 dataset I can't find anything with this.Could you please tell me what should I do?

**Comment by PeterL1n** [comment]
I just updated the repo README and added background download in the dataset section.

We are only going to release the validation set, which contains near 200 images with Creative Common license. The actual train set used in our project contains 8000+ images. They are crawled online and does not have CC license, so we won't be sharing the images.

For your purposes, you can try train with the small validation set to get started, or you can crawl more images yourself.
