### ISSUE TITLE
training question

### ISSUE THREAD

**Issue by PROMISELVKR** [PeterL1n/BackgroundMattingV2#87]
Hello! I trained the code 'train_refine.py' without any revise using my own dataset to get the pth file.However,I find the network structure I have got is different from the pretrained model you have provide:pytorch_mobilenetv2.The following image1 is your pretrained model structure and the second one image2 is mine
![dbe87887c67e6c02ed1a8263e51e583](https://user-images.githubusercontent.com/55682710/114826419-14b93900-9dfa-11eb-8ee8-acb38f98dc62.png)
image1
![1ba43d7265a1c20d260c80d32b9938c](https://user-images.githubusercontent.com/55682710/114826454-1c78dd80-9dfa-11eb-9347-100a2f4c321f.png)
image2
Could you please tell me why the network structure of mine has another 10 layers than yours? and if I want to change the code to get a model like yours,how should I do ?

2.Another question is that I test the model between yours and mine on CPU,I found that your model's flops is twice smaller than mine，which using the same training code.I don’t know if it’s because my network structure has 10 layers more than yours. Like the first question said.

my English is not good,sorry And I hope you can solve my doubts,Thank you!

**Comment by PeterL1n** [comment]
When you use the train script, did you set `--model-backbone mobilenetv2`?

**Comment by PROMISELVKR** [comment]
> When you use the train script, did you set `--model-backbone mobilenetv2`?

yes,I have done this,but still have the same result

**Comment by PROMISELVKR** [comment]
> When you use the train script, did you set `--model-backbone mobilenetv2`?

![image](https://user-images.githubusercontent.com/55682710/115104850-ce94de80-9f8d-11eb-8f3e-25418116c220.png)

**Comment by PeterL1n** [comment]
You have to understand one thing. the pytorch_mobilenetv2.pth file only contains the weights and it does not define model architecture. When you load it in python, the model architecture is defined by the code in `/model`, then you load the weights in pth. When you train your model, the architecture is also defined in `/model`. I don't know what you did wrong. You have to debug yourself.
