### ISSUE TITLE
how to run it realtime with 2080ti

### ISSUE THREAD

**Issue by luoww1992** [PeterL1n/BackgroundMattingV2#88]
i run it with torch version in 2080ti, but it runs very slowly, and the model speed of the onnx version is improved, but it cannot be real-time. What should I do to achieve the 4K and HD presentation effect?

**Comment by zhanghongyong123456** [comment]
model speed of the onnx version is improved？How did I get there? Why was I slow

**Comment by PeterL1n** [comment]
Just to clarify. If you are doing video conversion using inference_video.py, it is not expected to run in real-time. You will probably have 10fps-20fps speed.

This is because there are extra video encoding and decoding going on that is not fully optimized. The encoding and decoding is done on CPU, which could be changed to use hardware acceleration, etc. This are extra software engineering task that our research project will not include.

If you use the inference_speed_test.py, you will see the raw passthorugh speed through our model. For extra engineering work, we just leave out. The inference_video.py is only for demostration.

**Comment by luoww1992** [comment]
Q1: which model and type you used can be 4K/30fps and HD 60fps in the demo ?
the  torchScript/pytorch/onnx,   mobilenetv2 and so on ?

Q2:i want to run it as your test in real time with hardware acceleration,  can you give me some  suggestions ?


Q3:at the same time, i use the code to train  new model with a new dataset,  but i get a unexpected error：

```
Traceback (most recent call last):
  File "train_base_new.py", line 270, in <module>
    train()
  File "train_base_new.py", line 159, in train
    aug_shadow = T.RandomAffine(degrees=(-5, 5), translate=(0.2, 0.2), scale=(0.5, 1.5), shear=(-5, 5))(aug_shadow)
  File "/media/M_fM__VM__GM_fM_!M_#/Py38/KouTu/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 1204, in __call__
    ret = self.get_params(self.degrees, self.translate, self.scale, self.shear, img.size)
  File "/media/M_fM__VM__GM_fM_!M_#/Py38/KouTu/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 1174, in get_params
    max_dx = translate[0] * img_size[0]
TypeError: 'builtin_function_or_method' object is not subscriptable

```

when i change :
                aug_shadow = T.RandomAffine(degrees=(-5, 5), translate=(0.2, 0.2), scale=(0.5, 1.5), shear=(-5, 5))[aug_shadow]

wrong, show error:

```
Traceback (most recent call last):
  File "train_base_new.py", line 270, in <module>
    train()
  File "train_base_new.py", line 160, in train
    aug_shadow = T.RandomAffine(degrees=(-5, 5), translate=(0.2, 0.2), scale=(0.5, 1.5), shear=(-5, 5))[aug_shadow]
TypeError: 'RandomAffine' object is not subscriptable

```

and i can't find how to solve it in web.
What happened ?

**Comment by PeterL1n** [comment]
1. Use pytorch/torchscript
2. Maybe look into PyAV for hardware encoding / decoding if you want to do it in python. You also may need some threading for moving data to GPU in parallel, etc.
3. Maybe your torch/torchvision version is too old. Use the latest one, or try what is specified in `requirements.txt`

**Comment by luoww1992** [comment]
@PeterL1n 
how long you train it , when i train it i find the speed is slow, at last, i find it is slow in "__getitem__" to read imgs.
How did you solve i ？

**Comment by luoww1992** [comment]
@PeterL1n 
how long you train it , when i train it i find the speed is slow, at last, i find it is slow in "__getitem__" to read imgs.
How did you solve i ？

**Comment by PeterL1n** [comment]
@luoww1992 
Use VideoMatte240K SD version when training base. If loading image is slow, probably disk and CPU is the bottleneck.

**Comment by luoww1992** [comment]
@PeterL1n 
how long you train it , when i train it i find the speed is slow, at last, i find it is slow in "__getitem__" to read imgs.
How did you solve i ？

**Comment by luoww1992** [comment]
> @luoww1992
> Use VideoMatte240K SD version when training base. If loading image is slow, probably disk and CPU is the bottleneck.

Q1:so i need to train model with small size photos  in train_base,
after train_base,  train better model with HD  photos  in train_refine.?

Q2:i notice the size  when make dataset:
A.PairRandomAffineAndResize((512, 512)

1.what should i do if i change the size,  eg: 1152x576  or  <del> 960x540</del> ?

2.What to pay attention to if i change the size, maybe i have to match the deeplabv3 model without modification?

3. If you don’t use the deeplabv3 model, is it possible to change the size ?

4.If you don’t use the deeplabv3 model, what impact will it have on the model?

**Comment by decajcd** [comment]
> @PeterL1n
> 
> Q1: which model and type you used can be 4K/30fps and HD 60fps in the demo ?
> the torchScript/pytorch/onnx, mobilenetv2 and so on ?
> 
> Q2:i want to run it as your test in real time with hardware acceleration, can you give me some suggestions ?
> 
> Q3:at the same time, i use the code to train new model with a new dataset, but i get a unexpected error：
> 
> ```
> Traceback (most recent call last):
>   File "train_base_new.py", line 270, in <module>
>     train()
>   File "train_base_new.py", line 159, in train
>     aug_shadow = T.RandomAffine(degrees=(-5, 5), translate=(0.2, 0.2), scale=(0.5, 1.5), shear=(-5, 5))(aug_shadow)
>   File "/media/M_fM__VM__GM_fM_!M_#/Py38/KouTu/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 1204, in __call__
>     ret = self.get_params(self.degrees, self.translate, self.scale, self.shear, img.size)
>   File "/media/M_fM__VM__GM_fM_!M_#/Py38/KouTu/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 1174, in get_params
>     max_dx = translate[0] * img_size[0]
> TypeError: 'builtin_function_or_method' object is not subscriptable
> ```
> 
> when i change :
> aug_shadow = T.RandomAffine(degrees=(-5, 5), translate=(0.2, 0.2), scale=(0.5, 1.5), shear=(-5, 5))[aug_shadow]
> 
> wrong, show error:
> 
> ```
> Traceback (most recent call last):
>   File "train_base_new.py", line 270, in <module>
>     train()
>   File "train_base_new.py", line 160, in train
>     aug_shadow = T.RandomAffine(degrees=(-5, 5), translate=(0.2, 0.2), scale=(0.5, 1.5), shear=(-5, 5))[aug_shadow]
> TypeError: 'RandomAffine' object is not subscriptable
> ```
> 
> and i can't find how to solve it in web.
> What happened ?

How did you solve this problem？

**Comment by PeterL1n** [comment]
Not responsible for your custom code.

**Comment by decajcd** [comment]
> Not responsible for your custom code.

Traceback (most recent call last):
  File "train_base_new.py", line 270, in <module>
    train()
  File "train_base_new.py", line 159, in train
    aug_shadow = T.RandomAffine(degrees=(-5, 5), translate=(0.2, 0.2), scale=(0.5, 1.5), shear=(-5, 5))(aug_shadow)
  File "/media/M_fM__VM__GM_fM_!M_#/Py38/KouTu/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 1204, in __call__
    ret = self.get_params(self.degrees, self.translate, self.scale, self.shear, img.size)
  File "/media/M_fM__VM__GM_fM_!M_#/Py38/KouTu/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 1174, in get_params
    max_dx = translate[0] * img_size[0]
TypeError: 'builtin_function_or_method' object is not subscriptable
是这个问题，不是自己写的代码

**Comment by PeterL1n** [comment]
@decajcd What version of PyTorch and Torchvision are you using? Try 1.7 and up. Try use what's in the `requirements.txt`
