### ISSUE TITLE
the VideoMatte240K can't download from GoogleDrive

### ISSUE THREAD

**Issue by upperblacksmith** [PeterL1n/BackgroundMattingV2#90]
Download the VideoMatte240K dataset from GoogleDrive seems wrong. can you provide a baidu Pan download link?
thanks a lot.
![3696](https://user-images.githubusercontent.com/34127965/116342776-c2264680-a815-11eb-8f45-dcdb9617aa96.JPG)

**Comment by PeterL1n** [comment]
Okay. I will upload the datasets to Baidu Pan

**Comment by PeterL1n** [comment]
We have updated our dataset to Baidu Pan.

https://grail.cs.washington.edu/projects/background-matting-v2/#/datasets

**Comment by flow-dev** [comment]
Thank you for a very nice research and data !

I'm in a lot of trouble.
Download the VideoMatte240K dataset from GoogleDrive seems wrong too.
Also, baidu Pan does not download well from outside China.

Can you please put the HEVC-5GB dataset in an easily accessible location such as dropbox or a public server on campus?

**Comment by PeterL1n** [comment]
What's the problem you encountered by downloading from google drive?

There is a command-line tool called `gdown` that allows you to download on
servers.

Tips:
install gdown
use `gdown GOOGLE_DRIVE_FILE_URL_HERE`
but the gdown tool will fail at first. It will say that the url is not
recognized, but in the error message it will give you a suggestion
use the suggested url, and do gdown again.

Let me know if this helps.

Peter
