### ISSUE TITLE
Build it for windows OS 

### ISSUE THREAD

**Issue by elkhalafy** [PeterL1n/BackgroundMattingV2#92]
Can you build it for windows OS please ??

Also If you can create a plugin for obs studio.  This will be great too.. 

And I hope add email for you to send to you directly better than open subject here..

**Comment by PeterL1n** [comment]
PyTorch is available for Windows.

**Comment by elkhalafy** [comment]
Thank you for your answer me 

Where to download it? 
Can you give me link for download please?  thanks

**Comment by elkhalafy** [comment]
I need software for windows not Library or sdk to development one!  I'm not a developer!!

**Comment by elkhalafy** [comment]
If you can create android and IOS Apps .. This will be amazing and helpful.
