### ISSUE TITLE
AttributeError: 'RecursiveScriptModule' object has no attribute 'copy'

### ISSUE THREAD

**Issue by zhanghonglishanzai** [PeterL1n/BackgroundMattingV2#93]
I want to ask a question about "AttributeError: 'RecursiveScriptModule' object has no attribute 'copy'"

the following are my coding:

`(base) ubuntu@ubuntu:~/BM/BackgroundMattingV2$ python inference_video.py \
>         --model-type mattingrefine \
>         --model-backbone resnet50 \
>         --model-backbone-scale 0.25 \
>         --model-refine-mode sampling \
>         --model-refine-sample-pixels 80000 \
>         --model-checkpoint "/home/ubuntu/BM/content/torchscript_resnet50_fp32.pth" \
>         --video-src "/content/src.mp4" \
>         --video-bgr "/content/bgr.png" \
>         --output-dir "/content/output/" \
>         --output-type com fgr pha err ref
/home/ubuntu/anaconda3/envs/modnet_offline_3/lib/python3.6/site-packages/torch/serialization.py:589: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  " silence this warning)", UserWarning)
Traceback (most recent call last):
  File "inference_video.py", line 130, in <module>
    model.load_state_dict(torch.load(args.model_checkpoint, map_location=device), strict=False)
  File "/home/ubuntu/anaconda3/envs/modnet_offline_3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1196, in load_state_dict
    state_dict = state_dict.copy()
  File "/home/ubuntu/anaconda3/envs/modnet_offline_3/lib/python3.6/site-packages/torch/jit/_script.py", line 561, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/home/ubuntu/anaconda3/envs/modnet_offline_3/lib/python3.6/site-packages/torch/jit/_script.py", line 291, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/home/ubuntu/anaconda3/envs/modnet_offline_3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'RecursiveScriptModule' object has no attribute 'copy'
(base) ubuntu@ubuntu:~/BM/BackgroundMattingV2$ 
`

my environment is cuda11.1，pytorch 1.8.0, GEFORCE RTX 3090, 
and I suspect it's a problem with the pytorch version?
I

**Comment by PeterL1n** [comment]
You should use the pytorch weights instead of the torchscript weights here.

**Comment by zhanghonglishanzai** [comment]
我想问一下，为什么会有这个错误呢，我的cuda版本修改成了11.0，pytorch是1.7.0，按照道理说，不应该是版本不兼容的问题啊，我现在的错误还是AttributeError: 'RecursiveScriptModule' object has no attribute 'copy'

真的是很困扰啊

**Comment by zhanghonglishanzai** [comment]
https://blog.csdn.net/GeneralJing/article/details/109682176

我查到了这个解决方案，但是，代码中不是这个错误呀，哥哥们保存模型和加载模型都是对应的

**Comment by PeterL1n** [comment]
亲，跟你讲了，你这行错了
```
--model-checkpoint "/home/ubuntu/BM/content/torchscript_resnet50_fp32.pth" \
```

你不应该下载`torchscript_resnet50_fp32.pth`，要换成`pytorch_resnet50.pth`。

**Comment by zhanghonglishanzai** [comment]
好的呢，哥哥




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Peter ***@***.***&gt;; 
发送时间: 2021年5月12日(星期三) 下午4:26
收件人: ***@***.***&gt;; 
抄送: "Microsoft ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PeterL1n/BackgroundMattingV2] AttributeError: &#39;RecursiveScriptModule&#39; object has no attribute &#39;copy&#39; (#93)





 
亲，跟你讲了，你这行错了
 --model-checkpoint "/home/ubuntu/BM/content/torchscript_resnet50_fp32.pth" \  
你不应该下载torchscript_resnet50_fp32.pth，要换成pytorch_resnet50.pth。
