### ISSUE TITLE
What settings do I change to make the inference_video.py more sensitive to shadows? (COM )

### ISSUE THREAD

**Issue by Arudrin** [PeterL1n/BackgroundMattingV2#95]
Or simply improve results overall. Mobilenet backbone and model seems to work best but Id still like to improve on it more.

Here is the background image:
![vlcsnap-2021-05-12-19h54m33s456](https://user-images.githubusercontent.com/19412278/118088888-55f13880-b3fa-11eb-9ec9-c2da178ba08d.png)

A frame of the source video:
![src](https://user-images.githubusercontent.com/19412278/118088909-5be71980-b3fa-11eb-8a3e-e539a14cf104.png)

Frames of the result: There are  frames where the background is not completely replaced
![com1](https://user-images.githubusercontent.com/19412278/118088933-62759100-b3fa-11eb-9d60-2cd7ac6f1806.png)
![com2](https://user-images.githubusercontent.com/19412278/118088937-643f5480-b3fa-11eb-899e-1c1d5d3cfba9.png)

python command:

python inference_video.py \
        --model-type mattingrefine \
        --model-backbone mobilenetv2 \
        --model-backbone-scale 0.25 \
        --model-refine-mode sampling \
        --model-refine-sample-pixels 80000 \
        --model-checkpoint "path" \
        --video-src "xpath" \
        --video-bgr "ypath" \
        --video-resize 1920 1080 \
        --output-dir "zpath" \
        --output-type com

**Comment by PeterL1n** [comment]
I don't have any tricks that can help besides avoiding the shadow at its first place. Every method has its limitations. Shadow will cause problems even for green screen matting.

**Comment by Arudrin** [comment]
ok thank you very much!
