### ISSUE TITLE
inference_speed_test.py 是只用于图片的测试吗？可以用作视频的测试吗？

### ISSUE THREAD

**Issue by zhanghonglishanzai** [PeterL1n/BackgroundMattingV2#96]
我想测试在GPU下，视频的FPS，我看了一下代码，发现应该是测不了视频的，是这样吗？

The inference_speed_test.py script allows you to measure the tensor throughput of our model, which should achieve real-time. 

那上面这句话是上面意思呢？一张图片的实时性测试吗？

期待回复

**Comment by PeterL1n** [comment]
这个就是用于测视频FPS的

**Comment by zhanghonglishanzai** [comment]
好的，谢谢，解决了
