### ISSUE TITLE
请问是没有提供 高清的照片和对应的背景吗？？

### ISSUE THREAD

**Issue by zhanghonglishanzai** [PeterL1n/BackgroundMattingV2#98]
我想做一下inference_speed_test.py测试，现在可以下载到的照片以及对应的背景都是4K的，我想请教一下，高清的照片和对应的背景是还没有提供，是吗

**Comment by PeterL1n** [comment]
inference_speed_test.py 如果使用 refine-mode=sampling 是不需要提供图片的，只有你需要用 refine-mode=threshold 时需要。
